sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - PYTHON_TESTS=true TEST_SITE=false
  - PYTHON_TESTS=false TEST_SITE=docs
  - PYTHON_TESTS=false TEST_SITE=test_site
  - PYTHON_TESTS=false TEST_SITE=OSULUG/OSULUG-website

script:
  - bin/python-tests
  - bin/site-tests

notifications:
  email: false
  # irc:
  #   channels:
  #     - "chat.freenode.net#wok"
  #   on_success: always
  #   on_failure: always
